[workspace]
members = [
    "kompanion_core",
    "kompanion_sys",
    "kompanion_extractor",
    "kompanion_launcher",
]
resolver = "2"

[workspace.package]
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Marek"]
description = "This package allows the kindle UI to index epub files and open them in KOReader"

[workspace.package.metadata.manifest]
id = "kompanion"
name = "KOmpanion"
manifest_version = 2
supported_platforms = ["kindlehf", "kindlepw2"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
sha1 = "0.10"
log = "0.4"
epub-stream = "0.1"
url = "2"
zip = { version = "2", default-features = false, features = ["aes-crypto", "deflate64", "deflate", "lzma", "time"] }
cjson-bindings = { version = "0.6", features = ["std"] }
