[workspace]
members = [
    "kompanion_core",
    "kompanion_sys",
    "kompanion_extractor",
    "kompanion_launcher",
]
resolver = "2"

[workspace.package]
version = "0.1.8"
edition = "2021"
license = "MIT"
authors = ["Marek"]
description = "This package allows the kindle UI to index epub files and open them in KOReader"

[workspace.package.metadata.manifest]
id = "kompanion"
name = "KOmpanion"
manifest_version = 2
supported_platforms = ["kindlehf", "kindlepw2"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.23"
sha1 = "0.11"
log = "0.4"
epub-stream = "0.1"
url = "2"
zip = "8"
hex = "0.4.3"
fb2 = "0.4.4"
quick-xml = { version = "0.41", features = ["encoding", "serialize"] }
cjson-bindings = { version = "0.6", features = ["std"] }
