[package]
name = "kompanion_sys"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
cjson-bindings = { workspace = true }

[features]
default = []
mock-scanner = []
mock-lipc = []
real-scanner = []
real-lipc = []
link-scanner = []
link-lipc = []
