[package]
name = "koreader_companion_extractor"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
koreader_companion_core = { path = "../koreader_companion_core" }
koreader_companion_sys = { path = "../koreader_companion_sys" }
serde_json = { workspace = true }
epub-stream = { workspace = true }
zip = { workspace = true }
log = { workspace = true }
