[build]
target = "armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-kindlehf-linux-gnueabihf-gcc"

[profile.release]
opt-level = 3
lto = true
strip = true

[alias]
build-all = "build --release --features real-lipc,real-scanner --target armv7-unknown-linux-gnueabihf" # --target armv7-unknown-linux-gnueabi
