[package]
name = "sh_integration_extractor"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
sh_integration_core = { path = "../sh_integration_core" }
sh_integration_sys = { path = "../sh_integration_sys" }
serde_json = { workspace = true }
log = { workspace = true }
