[package]
name = "kompanion_extractor"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
kompanion_core = { path = "../kompanion_core" }
kompanion_sys = { path = "../kompanion_sys" }
cjson-bindings = { workspace = true }
epub-stream = { workspace = true }
zip = { workspace = true }
fb2 = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true }
quick-xml = { version = "0.41", features = ["encoding", "serialize"] }
log = { workspace = true }
simplelog = { version = "0.12", default-features = false }
