name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build
      continue-on-error: true
      run: |
          sudo apt update
          sudo apt install g++-14 python3 python3-pip python3-setuptools python3-wheel ninja-build
          pip3 install meson
          meson setup builddir
          meson test -C builddir
    - uses: actions/upload-artifact@v4
      with:
        name: kompanion-tests_logs
        path: builddir/meson-logs

  build-kindle:
    runs-on: ubuntu-latest

    steps:
    - name: Download toolchain
      run: wget -q https://github.com/KindleModding/koxtoolchain/releases/latest/download/kindle.tar.gz -O - | tar -xzf - -C ~

    - uses: actions/checkout@v4
      with:
        repository: KindleModding/kindle-sdk
        submodules: recursive
        path: kindle-sdk
    - name: "Setup kindle-sdk"
      run: |
          sudo apt update
          sudo apt install -y zlib1g-dev libarchive-dev nettle-dev curl
          bash ./kindle-sdk/gen-sdk.sh kindle

    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build
      run: |
          sudo apt install g++-14 python3 python3-pip python3-setuptools python3-wheel ninja-build
          pip3 install meson
          meson setup --cross-file ~/x-tools/arm-kindle-linux-gnueabi/meson-crosscompile.txt builddir_kindle
          meson compile -C builddir_kindle
    - uses: actions/upload-artifact@v4
      with:
        name: kompanion-kindle
        path: builddir_kindle

  build-kindle5:
    runs-on: ubuntu-latest

    steps:
    - name: Download toolchain
      run: wget -q https://github.com/KindleModding/koxtoolchain/releases/latest/download/kindle5.tar.gz -O - | tar -xzf - -C ~

    - uses: actions/checkout@v4
      with:
        repository: KindleModding/kindle-sdk
        submodules: recursive
        path: kindle-sdk
    - name: "Setup kindle-sdk"
      run: |
          sudo apt update
          sudo apt install -y zlib1g-dev libarchive-dev nettle-dev curl
          bash ./kindle-sdk/gen-sdk.sh kindle5

    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build
      run: |
          sudo apt install g++-14 python3 python3-pip python3-setuptools python3-wheel ninja-build
          pip3 install meson
          meson setup --cross-file ~/x-tools/arm-kindle5-linux-gnueabi/meson-crosscompile.txt builddir_kindle5
          meson compile -C builddir_kindle5
    - uses: actions/upload-artifact@v4
      with:
        name: kompanion-kindle5
        path: builddir_kindle5

  build-kindlepw2:
    runs-on: ubuntu-latest

    steps:
    - name: Download toolchain
      run: wget -q https://github.com/KindleModding/koxtoolchain/releases/latest/download/kindlepw2.tar.gz -O - | tar -xzf - -C ~

    - uses: actions/checkout@v4
      with:
        repository: KindleModding/kindle-sdk
        submodules: recursive
        path: kindle-sdk
    - name: "Setup kindle-sdk"
      run: |
          sudo apt update
          sudo apt install -y zlib1g-dev libarchive-dev nettle-dev curl
          bash ./kindle-sdk/gen-sdk.sh kindlepw2

    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build
      run: |
          sudo apt install g++-14 python3 python3-pip python3-setuptools python3-wheel ninja-build
          pip3 install meson
          meson setup --cross-file ~/x-tools/arm-kindlepw2-linux-gnueabi/meson-crosscompile.txt builddir_kindlepw2
          meson compile -C builddir_kindlepw2
    - uses: actions/upload-artifact@v4
      with:
        name: kompanion-kindlepw2
        path: builddir_kindlepw2

  build-kindlehf:
    runs-on: ubuntu-latest

    steps:
    - name: Download toolchain
      run: wget -q https://github.com/KindleModding/koxtoolchain/releases/latest/download/kindlehf.tar.gz -O - | tar -xzf - -C ~

    - uses: actions/checkout@v4
      with:
        repository: KindleModding/kindle-sdk
        submodules: recursive
        path: kindle-sdk
    - name: "Setup kindle-sdk"
      run: |
          sudo apt update
          sudo apt install -y zlib1g-dev libarchive-dev nettle-dev curl
          bash ./kindle-sdk/gen-sdk.sh kindlehf

    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build
      run: |
          sudo apt install g++-14 python3 python3-pip python3-setuptools python3-wheel ninja-build
          pip3 install meson
          meson setup --cross-file ~/x-tools/arm-kindlehf-linux-gnueabihf/meson-crosscompile.txt builddir_kindlehf
          meson compile -C builddir_kindlehf
    - uses: actions/upload-artifact@v4
      with:
        name: kompanion-kindlehf
        path: builddir_kindlehf
